# Use an official PostgreSQL as the base image
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=parkinglot
ENV POSTGRES_USER=rootparking
ENV POSTGRES_PASSWORD=rootparking

# Expose the PostgreSQL port (5432) to the host
EXPOSE 5432
